import { useEffect, useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import Timeline from "@/components/Timeline";
import { fetchWithAuth } from "@/utils/api";

const API = "http://127.0.0.1:8000";

type GenerateState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "success"; url: string }
  | { status: "error"; message: string };

export default function App() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [username, setUsername] = useState<string | null>(null);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [generateState, setGenerateState] = useState<GenerateState>({ status: "idle" });
  const [playlistName, setPlaylistName] = useState("Discovery Playlist");
  const [playlistDesc, setPlaylistDesc] = useState("Generated by Musifind");

  // Handle token from redirect
  useEffect(() => {
    const token = searchParams.get("access_token");
    const refresh = searchParams.get("refresh_token");
    if (token) {
      localStorage.setItem("spotify_token", token);
      if (refresh) localStorage.setItem("spotify_refresh", refresh);
      navigate("/", { replace: true });
      setIsAuthenticated(true);
    } else {
      const stored = localStorage.getItem("spotify_token");
      setIsAuthenticated(!!stored);
    }
  }, [searchParams, navigate]);

  // Fetch username
  useEffect(() => {
    if (!isAuthenticated) return;
    fetchWithAuth(`${API}/me`)
      .then((r) => r.json())
      .then((d) => setUsername(d.display_name ?? null))
      .catch(() => {});
  }, [isAuthenticated]);

  function toggleTrack(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
    // Reset generate state on selection change
    setGenerateState({ status: "idle" });
  }

  async function handleGenerate() {
    if (selectedIds.size === 0) return;
    setGenerateState({ status: "loading" });
    try {
      const res = await fetchWithAuth(`${API}/generate-playlist`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ 
          seed_track_ids: Array.from(selectedIds),
          playlist_name: playlistName,
          playlist_description: playlistDesc
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail ?? "Unknown error");
      setGenerateState({ status: "success", url: data.url });
    } catch (e: any) {
      setGenerateState({ status: "error", message: e.message });
    }
  }

  if (!isAuthenticated) {
    return (
      <main className="min-h-screen w-full bg-[#0d0d0d] flex flex-col items-center justify-center gap-6">
        <div className="text-center space-y-2">
          <h1 className="text-5xl font-bold text-white tracking-tight">
            Spoti<span className="text-[#b3b3b3]">find</span>
          </h1>
          <p className="text-[#6b6b6b] text-base">
            Rediscover your music journey through time
          </p>
        </div>
        <a
          href={`${API}/login`}
          className="flex items-center gap-3 px-7 py-3.5 rounded border border-[#2a2a2a] bg-[#1a1a1a] text-white font-semibold text-sm hover:bg-[#222] hover:border-[#3a3a3a] transition-colors"
        >
          <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z" />
          </svg>
          Connect with Spotify
        </a>
        <p className="text-[#4a4a4a] text-xs">
          Sign in with your Spotify account to get started
        </p>
      </main>
    );
  }

  return (
    <main className="min-h-screen w-full bg-[#0d0d0d] text-white">
      {/* 3-Column Grid */}
      <div className="grid grid-cols-[280px_1fr_300px] min-h-screen divide-x divide-[#1e1e1e]">

        {/* ── Left Column ─────────────────────────────────────── */}
        <aside className="flex flex-col gap-8 p-8 border-r border-[#1e1e1e]">
          {/* Brand */}
          <div>
            <h1 className="text-xl font-bold text-white tracking-tight mb-1">
              Spoti<span className="text-[#a0a0a0]">find</span>
            </h1>
            <div className="w-8 h-px bg-[#2a2a2a] mb-4" />
            <p className="text-[#6b6b6b] text-sm leading-relaxed">
              Generate personalized playlists to discover your next favorite song.
            </p>
          </div>

          {/* User */}
          <div className="border border-[#1e1e1e] rounded p-4 bg-[#111]">
            <p className="text-[#4a4a4a] text-[10px] uppercase tracking-widest font-semibold mb-2">
              Signed in as
            </p>
            {username ? (
              <p className="text-white text-sm font-medium truncate">{username}</p>
            ) : (
              <div className="h-4 w-24 bg-[#1e1e1e] rounded animate-pulse" />
            )}
          </div>

          {/* Instructions */}
          <div className="space-y-3">
            <Step n={1} label="Select tracks from your timeline" />
            <Step n={2} label="Click Generate to build a playlist" />
            <Step n={3} label="Open it directly on Spotify" />
          </div>
        </aside>

        {/* ── Middle Column ────────────────────────────────────── */}
        <section className="overflow-y-auto h-screen">
          <Timeline
            selectedIds={selectedIds}
            onToggleTrack={toggleTrack}
          />
        </section>

        {/* ── Right Column ─────────────────────────────────────── */}
        <aside className="flex flex-col gap-6 p-8 border-l border-[#1e1e1e]">
          <div>
            <p className="text-[#4a4a4a] text-[10px] uppercase tracking-widest font-semibold mb-1">
              Generator
            </p>
            <h2 className="text-base font-semibold text-white">Generate Playlist</h2>
          </div>

          {/* Selection counter */}
          <div className="border border-[#1e1e1e] rounded p-4 bg-[#111] flex items-center justify-between">
            <span className="text-[#6b6b6b] text-sm">Selected songs</span>
            <span className="text-white text-xl font-bold tabular-nums">
              {selectedIds.size}
            </span>
          </div>

          {selectedIds.size > 0 && (
            <p className="text-[#4a4a4a] text-xs -mt-2">
              {selectedIds.size > 5
                ? `5 of ${selectedIds.size} will be used as seeds`
                : "All selected will be used as seeds"}
            </p>
          )}

          {/* Generate inputs */}
          {selectedIds.size > 0 && (
            <div className="space-y-3 mt-4 mb-4">
              <div>
                <label className="text-[#6b6b6b] text-xs mb-1 block">Playlist Name</label>
                <input
                  type="text"
                  value={playlistName}
                  onChange={(e) => setPlaylistName(e.target.value)}
                  className="w-full bg-[#111] border border-[#1e1e1e] rounded px-3 py-2 text-sm text-white focus:outline-none focus:border-[#3a3a3a] transition-colors"
                />
              </div>
              <div>
                <label className="text-[#6b6b6b] text-xs mb-1 block">Description</label>
                <textarea
                  value={playlistDesc}
                  onChange={(e) => setPlaylistDesc(e.target.value)}
                  className="w-full bg-[#111] border border-[#1e1e1e] rounded px-3 py-2 text-sm text-white focus:outline-none focus:border-[#3a3a3a] transition-colors resize-none h-20"
                />
              </div>
            </div>
          )}

          {/* Generate button */}
          <button
            id="generate-playlist-btn"
            onClick={handleGenerate}
            disabled={selectedIds.size === 0 || generateState.status === "loading"}
            className="w-full py-3 rounded text-sm font-semibold transition-colors
              bg-[#1a1a1a] border border-[#2a2a2a] text-white
              hover:bg-[#222] hover:border-[#3a3a3a]
              disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {generateState.status === "loading" ? (
              <span className="flex items-center justify-center gap-2">
                <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Generating…
              </span>
            ) : (
              "Generate to Spotify"
            )}
          </button>

          {/* Result */}
          {generateState.status === "success" && (
            <div className="border border-[#1e1e1e] rounded p-4 bg-[#111] space-y-2">
              <p className="text-[#6b6b6b] text-xs">Playlist created!</p>
              <a
                href={generateState.url}
                target="_blank"
                rel="noopener noreferrer"
                className="block text-sm font-medium text-white underline underline-offset-2 hover:text-[#b3b3b3] transition-colors break-all"
              >
                Open in Spotify ↗
              </a>
            </div>
          )}

          {generateState.status === "error" && (
            <div className="border border-[#2a1010] rounded p-4 bg-[#110a0a]">
              <p className="text-red-400 text-xs">{generateState.message}</p>
            </div>
          )}

          {/* Clear selection */}
          {selectedIds.size > 0 && (
            <button
              onClick={() => {
                setSelectedIds(new Set());
                setGenerateState({ status: "idle" });
              }}
              className="text-[#4a4a4a] text-xs hover:text-[#6b6b6b] transition-colors text-left"
            >
              Clear selection
            </button>
          )}
        </aside>
      </div>
    </main>
  );
}

function Step({ n, label }: { n: number; label: string }) {
  return (
    <div className="flex items-start gap-3">
      <span className="flex-shrink-0 w-5 h-5 rounded border border-[#2a2a2a] bg-[#1a1a1a] text-[#6b6b6b] text-[10px] font-bold flex items-center justify-center">
        {n}
      </span>
      <p className="text-[#6b6b6b] text-xs leading-relaxed pt-0.5">{label}</p>
    </div>
  );
}
